### Send Input
POST http://localhost:5000/hash
Content-Type: application/json

{
    "seeds": [
        "abc",
        "def",
        "xyz"
    ]
}

### Send Input
GET http://localhost:5000/hash
